In [87]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import seaborn as sns
import numpy as np
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from sklearn import naive_bayes
from sklearn import datasets
from sklearn import metrics

In [81]:
dataset = datasets.load_wine()
X = dataset.data
y = dataset.target

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [104]:
model1 = naive_bayes.BernoulliNB()
model1.fit(X_train, y_train)
print(model1)
expected_y  = y_test
predicted_y = model1.predict(X_test)

BernoulliNB()


In [105]:
print(metrics.classification_report(expected_y, predicted_y, target_names=dataset.target_names))
print(metrics.confusion_matrix(expected_y, predicted_y))


              precision    recall  f1-score   support

     class_0       0.00      0.00      0.00        14
     class_1       0.38      1.00      0.55        17
     class_2       0.00      0.00      0.00        14

    accuracy                           0.38        45
   macro avg       0.13      0.33      0.18        45
weighted avg       0.14      0.38      0.21        45

[[ 0 14  0]
 [ 0 17  0]
 [ 0 14  0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [106]:
model2 = naive_bayes.GaussianNB()
model2.fit(X_train, y_train)
print(model2)
expected_y  = y_test
predicted_y = model2.predict(X_test)

GaussianNB()


In [107]:
print(metrics.classification_report(expected_y, predicted_y, target_names=dataset.target_names))
print(metrics.confusion_matrix(expected_y, predicted_y))


              precision    recall  f1-score   support

     class_0       0.93      0.93      0.93        14
     class_1       0.94      0.94      0.94        17
     class_2       1.00      1.00      1.00        14

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[13  1  0]
 [ 1 16  0]
 [ 0  0 14]]


In [109]:
model3 = naive_bayes.MultinomialNB()
model3.fit(X_train, y_train)
print(model3)
expected_y  = y_test
predicted_y = model3.predict(X_test)

MultinomialNB()


In [110]:
print(metrics.classification_report(expected_y, predicted_y, target_names=dataset.target_names))
print(metrics.confusion_matrix(expected_y, predicted_y))


              precision    recall  f1-score   support

     class_0       0.93      0.93      0.93        14
     class_1       0.83      0.88      0.86        17
     class_2       0.92      0.86      0.89        14

    accuracy                           0.89        45
   macro avg       0.89      0.89      0.89        45
weighted avg       0.89      0.89      0.89        45

[[13  1  0]
 [ 1 15  1]
 [ 0  2 12]]
